# Generated by Django 5.2.6 on 2025-09-24 10:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_propuesta_voto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='interesados',
            field=models.ManyToManyField(blank=True, related_name='articulos_interesados', to=settings.AUTH_USER_MODEL),
        ),
    ]
